services:
  app:
    build: .
    container_name: dea
    volumes:
      - ./cache:/app/cache
      - ./config:/app/config
    env_file:
      - .env
    command: bun run start
    restart: unless-stopped